/*
 * Edison Credentials API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sicpa.edison.credentialsclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sicpa.edison.credentialsclient.model.IndyProofReqNonRevoked;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * IndyProofReqAttrSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-15T13:20:26.194789+01:00[Europe/Zurich]")
public class IndyProofReqAttrSpec {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NAMES = "names";
  @SerializedName(SERIALIZED_NAME_NAMES)
  private List<String> names = null;

  public static final String SERIALIZED_NAME_NON_REVOKED = "nonRevoked";
  @SerializedName(SERIALIZED_NAME_NON_REVOKED)
  private IndyProofReqNonRevoked nonRevoked;

  public static final String SERIALIZED_NAME_RESTRICTIONS = "restrictions";
  @SerializedName(SERIALIZED_NAME_RESTRICTIONS)
  private List<Map<String, String>> restrictions = null;


  public IndyProofReqAttrSpec name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public IndyProofReqAttrSpec names(List<String> names) {
    
    this.names = names;
    return this;
  }

  public IndyProofReqAttrSpec addNamesItem(String namesItem) {
    if (this.names == null) {
      this.names = new ArrayList<>();
    }
    this.names.add(namesItem);
    return this;
  }

   /**
   * Get names
   * @return names
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getNames() {
    return names;
  }


  public void setNames(List<String> names) {
    this.names = names;
  }


  public IndyProofReqAttrSpec nonRevoked(IndyProofReqNonRevoked nonRevoked) {
    
    this.nonRevoked = nonRevoked;
    return this;
  }

   /**
   * Get nonRevoked
   * @return nonRevoked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public IndyProofReqNonRevoked getNonRevoked() {
    return nonRevoked;
  }


  public void setNonRevoked(IndyProofReqNonRevoked nonRevoked) {
    this.nonRevoked = nonRevoked;
  }


  public IndyProofReqAttrSpec restrictions(List<Map<String, String>> restrictions) {
    
    this.restrictions = restrictions;
    return this;
  }

  public IndyProofReqAttrSpec addRestrictionsItem(Map<String, String> restrictionsItem) {
    if (this.restrictions == null) {
      this.restrictions = new ArrayList<>();
    }
    this.restrictions.add(restrictionsItem);
    return this;
  }

   /**
   * Get restrictions
   * @return restrictions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Map<String, String>> getRestrictions() {
    return restrictions;
  }


  public void setRestrictions(List<Map<String, String>> restrictions) {
    this.restrictions = restrictions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndyProofReqAttrSpec indyProofReqAttrSpec = (IndyProofReqAttrSpec) o;
    return Objects.equals(this.name, indyProofReqAttrSpec.name) &&
        Objects.equals(this.names, indyProofReqAttrSpec.names) &&
        Objects.equals(this.nonRevoked, indyProofReqAttrSpec.nonRevoked) &&
        Objects.equals(this.restrictions, indyProofReqAttrSpec.restrictions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, names, nonRevoked, restrictions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndyProofReqAttrSpec {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("    nonRevoked: ").append(toIndentedString(nonRevoked)).append("\n");
    sb.append("    restrictions: ").append(toIndentedString(restrictions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

