/*
 * Edison Credentials API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sicpa.edison.credentialsclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OrganizationUpdate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-10T15:22:45.234670+01:00[Europe/Zurich]")
public class OrganizationUpdate {
  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_HOST = "host";
  @SerializedName(SERIALIZED_NAME_HOST)
  private String host;

  public static final String SERIALIZED_NAME_DID_TO_PUBLISH = "didToPublish";
  @SerializedName(SERIALIZED_NAME_DID_TO_PUBLISH)
  private String didToPublish;


  public OrganizationUpdate label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * The organization label
   * @return label
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The organization label")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    this.label = label;
  }


  public OrganizationUpdate host(String host) {
    
    this.host = host;
    return this;
  }

   /**
   * The organization host
   * @return host
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The organization host")

  public String getHost() {
    return host;
  }


  public void setHost(String host) {
    this.host = host;
  }


  public OrganizationUpdate didToPublish(String didToPublish) {
    
    this.didToPublish = didToPublish;
    return this;
  }

   /**
   * The DID to be set as the wallet&#39;s public DID
   * @return didToPublish
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The DID to be set as the wallet's public DID")

  public String getDidToPublish() {
    return didToPublish;
  }


  public void setDidToPublish(String didToPublish) {
    this.didToPublish = didToPublish;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationUpdate organizationUpdate = (OrganizationUpdate) o;
    return Objects.equals(this.label, organizationUpdate.label) &&
        Objects.equals(this.host, organizationUpdate.host) &&
        Objects.equals(this.didToPublish, organizationUpdate.didToPublish);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, host, didToPublish);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationUpdate {\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    didToPublish: ").append(toIndentedString(didToPublish)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

