/*
 * Edison Credentials API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sicpa.edison.credentialsclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * RevocationRequirement
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-08T17:35:55.199434+02:00[Europe/Zurich]")
public class RevocationRequirement {
  public static final String SERIALIZED_NAME_VALID_AT = "validAt";
  @SerializedName(SERIALIZED_NAME_VALID_AT)
  private OffsetDateTime validAt;

  public static final String SERIALIZED_NAME_VALID_NOW = "validNow";
  @SerializedName(SERIALIZED_NAME_VALID_NOW)
  private Boolean validNow;


  public RevocationRequirement validAt(OffsetDateTime validAt) {
    
    this.validAt = validAt;
    return this;
  }

   /**
   * Date at which the credential should be valid
   * @return validAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date at which the credential should be valid")

  public OffsetDateTime getValidAt() {
    return validAt;
  }


  public void setValidAt(OffsetDateTime validAt) {
    this.validAt = validAt;
  }


  public RevocationRequirement validNow(Boolean validNow) {
    
    this.validNow = validNow;
    return this;
  }

   /**
   * Defines if the credential should be valid at the current date
   * @return validNow
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Defines if the credential should be valid at the current date")

  public Boolean getValidNow() {
    return validNow;
  }


  public void setValidNow(Boolean validNow) {
    this.validNow = validNow;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RevocationRequirement revocationRequirement = (RevocationRequirement) o;
    return Objects.equals(this.validAt, revocationRequirement.validAt) &&
        Objects.equals(this.validNow, revocationRequirement.validNow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(validAt, validNow);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RevocationRequirement {\n");
    sb.append("    validAt: ").append(toIndentedString(validAt)).append("\n");
    sb.append("    validNow: ").append(toIndentedString(validNow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

