/*
 * Edison Credentials API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sicpa.edison.credentialsclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Schema
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-11T17:14:05.875852+01:00[Europe/Zurich]")
public class Schema {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  public static final String SERIALIZED_NAME_ATTRIBUTES_NAME = "attributesName";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES_NAME)
  private List<String> attributesName = null;


  public Schema id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The schema&#39;s id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The schema's id")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Schema name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The schema&#39;s name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The schema's name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Schema version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * The schema&#39;s version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The schema's version")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public Schema attributesName(List<String> attributesName) {
    
    this.attributesName = attributesName;
    return this;
  }

  public Schema addAttributesNameItem(String attributesNameItem) {
    if (this.attributesName == null) {
      this.attributesName = new ArrayList<>();
    }
    this.attributesName.add(attributesNameItem);
    return this;
  }

   /**
   * The schema&#39;s attributes
   * @return attributesName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The schema's attributes")

  public List<String> getAttributesName() {
    return attributesName;
  }


  public void setAttributesName(List<String> attributesName) {
    this.attributesName = attributesName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Schema schema = (Schema) o;
    return Objects.equals(this.id, schema.id) &&
        Objects.equals(this.name, schema.name) &&
        Objects.equals(this.version, schema.version) &&
        Objects.equals(this.attributesName, schema.attributesName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, version, attributesName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Schema {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    attributesName: ").append(toIndentedString(attributesName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

