/*
 * Edison Credentials API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sicpa.edison.credentialsclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * VerificationParam
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-10T15:13:18.986882+01:00[Europe/Zurich]")
public class VerificationParam {
  public static final String SERIALIZED_NAME_VERIFICATION_TEMPLATE_NAME = "verificationTemplateName";
  @SerializedName(SERIALIZED_NAME_VERIFICATION_TEMPLATE_NAME)
  private String verificationTemplateName;

  public static final String SERIALIZED_NAME_CONNECTION_ID = "connectionId";
  @SerializedName(SERIALIZED_NAME_CONNECTION_ID)
  private String connectionId;


  public VerificationParam verificationTemplateName(String verificationTemplateName) {
    
    this.verificationTemplateName = verificationTemplateName;
    return this;
  }

   /**
   * The verificationTemplate name
   * @return verificationTemplateName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "example", value = "The verificationTemplate name")

  public String getVerificationTemplateName() {
    return verificationTemplateName;
  }


  public void setVerificationTemplateName(String verificationTemplateName) {
    this.verificationTemplateName = verificationTemplateName;
  }


  public VerificationParam connectionId(String connectionId) {
    
    this.connectionId = connectionId;
    return this;
  }

   /**
   * The connection id
   * @return connectionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3fa85f64-5717-4562-b3fc-2c963f66afa6", value = "The connection id")

  public String getConnectionId() {
    return connectionId;
  }


  public void setConnectionId(String connectionId) {
    this.connectionId = connectionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerificationParam verificationParam = (VerificationParam) o;
    return Objects.equals(this.verificationTemplateName, verificationParam.verificationTemplateName) &&
        Objects.equals(this.connectionId, verificationParam.connectionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(verificationTemplateName, connectionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerificationParam {\n");
    sb.append("    verificationTemplateName: ").append(toIndentedString(verificationTemplateName)).append("\n");
    sb.append("    connectionId: ").append(toIndentedString(connectionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

