/*
 * Edison Credentials API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sicpa.edison.credentialsclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The original validation request
 */
@ApiModel(description = "The original validation request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-15T13:20:26.194789+01:00[Europe/Zurich]")
public class VerificationRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NONCE = "nonce";
  @SerializedName(SERIALIZED_NAME_NONCE)
  private String nonce;

  public static final String SERIALIZED_NAME_REQUESTED_ATTRIBUTES = "requestedAttributes";
  @SerializedName(SERIALIZED_NAME_REQUESTED_ATTRIBUTES)
  private Map<String, Object> requestedAttributes = null;

  public static final String SERIALIZED_NAME_REQUESTED_PREDICATES = "requestedPredicates";
  @SerializedName(SERIALIZED_NAME_REQUESTED_PREDICATES)
  private Map<String, Object> requestedPredicates = null;


  public VerificationRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public VerificationRequest nonce(String nonce) {
    
    this.nonce = nonce;
    return this;
  }

   /**
   * Get nonce
   * @return nonce
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNonce() {
    return nonce;
  }


  public void setNonce(String nonce) {
    this.nonce = nonce;
  }


  public VerificationRequest requestedAttributes(Map<String, Object> requestedAttributes) {
    
    this.requestedAttributes = requestedAttributes;
    return this;
  }

  public VerificationRequest putRequestedAttributesItem(String key, Object requestedAttributesItem) {
    if (this.requestedAttributes == null) {
      this.requestedAttributes = new HashMap<>();
    }
    this.requestedAttributes.put(key, requestedAttributesItem);
    return this;
  }

   /**
   * Get requestedAttributes
   * @return requestedAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, Object> getRequestedAttributes() {
    return requestedAttributes;
  }


  public void setRequestedAttributes(Map<String, Object> requestedAttributes) {
    this.requestedAttributes = requestedAttributes;
  }


  public VerificationRequest requestedPredicates(Map<String, Object> requestedPredicates) {
    
    this.requestedPredicates = requestedPredicates;
    return this;
  }

  public VerificationRequest putRequestedPredicatesItem(String key, Object requestedPredicatesItem) {
    if (this.requestedPredicates == null) {
      this.requestedPredicates = new HashMap<>();
    }
    this.requestedPredicates.put(key, requestedPredicatesItem);
    return this;
  }

   /**
   * Get requestedPredicates
   * @return requestedPredicates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, Object> getRequestedPredicates() {
    return requestedPredicates;
  }


  public void setRequestedPredicates(Map<String, Object> requestedPredicates) {
    this.requestedPredicates = requestedPredicates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerificationRequest verificationRequest = (VerificationRequest) o;
    return Objects.equals(this.name, verificationRequest.name) &&
        Objects.equals(this.nonce, verificationRequest.nonce) &&
        Objects.equals(this.requestedAttributes, verificationRequest.requestedAttributes) &&
        Objects.equals(this.requestedPredicates, verificationRequest.requestedPredicates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, nonce, requestedAttributes, requestedPredicates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerificationRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("    requestedAttributes: ").append(toIndentedString(requestedAttributes)).append("\n");
    sb.append("    requestedPredicates: ").append(toIndentedString(requestedPredicates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

