/*
 * Edison Credentials API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sicpa.edison.credentialsclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sicpa.edison.credentialsclient.model.IndyProofReqAttrSpec;
import com.sicpa.edison.credentialsclient.model.IndyProofReqNonRevoked;
import com.sicpa.edison.credentialsclient.model.IndyProofReqPredSpec;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * VerificationTemplateContent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-11T17:14:05.875852+01:00[Europe/Zurich]")
public class VerificationTemplateContent {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NON_REVOKED = "nonRevoked";
  @SerializedName(SERIALIZED_NAME_NON_REVOKED)
  private IndyProofReqNonRevoked nonRevoked;

  public static final String SERIALIZED_NAME_REQUESTED_ATTRIBUTES = "requestedAttributes";
  @SerializedName(SERIALIZED_NAME_REQUESTED_ATTRIBUTES)
  private Map<String, IndyProofReqAttrSpec> requestedAttributes = null;

  public static final String SERIALIZED_NAME_REQUESTED_PREDICATES = "requestedPredicates";
  @SerializedName(SERIALIZED_NAME_REQUESTED_PREDICATES)
  private Map<String, IndyProofReqPredSpec> requestedPredicates = null;


  public VerificationTemplateContent name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The verificationTemplate name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "example", value = "The verificationTemplate name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public VerificationTemplateContent nonRevoked(IndyProofReqNonRevoked nonRevoked) {
    
    this.nonRevoked = nonRevoked;
    return this;
  }

   /**
   * Get nonRevoked
   * @return nonRevoked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public IndyProofReqNonRevoked getNonRevoked() {
    return nonRevoked;
  }


  public void setNonRevoked(IndyProofReqNonRevoked nonRevoked) {
    this.nonRevoked = nonRevoked;
  }


  public VerificationTemplateContent requestedAttributes(Map<String, IndyProofReqAttrSpec> requestedAttributes) {
    
    this.requestedAttributes = requestedAttributes;
    return this;
  }

  public VerificationTemplateContent putRequestedAttributesItem(String key, IndyProofReqAttrSpec requestedAttributesItem) {
    if (this.requestedAttributes == null) {
      this.requestedAttributes = new HashMap<>();
    }
    this.requestedAttributes.put(key, requestedAttributesItem);
    return this;
  }

   /**
   * Get requestedAttributes
   * @return requestedAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, IndyProofReqAttrSpec> getRequestedAttributes() {
    return requestedAttributes;
  }


  public void setRequestedAttributes(Map<String, IndyProofReqAttrSpec> requestedAttributes) {
    this.requestedAttributes = requestedAttributes;
  }


  public VerificationTemplateContent requestedPredicates(Map<String, IndyProofReqPredSpec> requestedPredicates) {
    
    this.requestedPredicates = requestedPredicates;
    return this;
  }

  public VerificationTemplateContent putRequestedPredicatesItem(String key, IndyProofReqPredSpec requestedPredicatesItem) {
    if (this.requestedPredicates == null) {
      this.requestedPredicates = new HashMap<>();
    }
    this.requestedPredicates.put(key, requestedPredicatesItem);
    return this;
  }

   /**
   * Get requestedPredicates
   * @return requestedPredicates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, IndyProofReqPredSpec> getRequestedPredicates() {
    return requestedPredicates;
  }


  public void setRequestedPredicates(Map<String, IndyProofReqPredSpec> requestedPredicates) {
    this.requestedPredicates = requestedPredicates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerificationTemplateContent verificationTemplateContent = (VerificationTemplateContent) o;
    return Objects.equals(this.name, verificationTemplateContent.name) &&
        Objects.equals(this.nonRevoked, verificationTemplateContent.nonRevoked) &&
        Objects.equals(this.requestedAttributes, verificationTemplateContent.requestedAttributes) &&
        Objects.equals(this.requestedPredicates, verificationTemplateContent.requestedPredicates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, nonRevoked, requestedAttributes, requestedPredicates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerificationTemplateContent {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nonRevoked: ").append(toIndentedString(nonRevoked)).append("\n");
    sb.append("    requestedAttributes: ").append(toIndentedString(requestedAttributes)).append("\n");
    sb.append("    requestedPredicates: ").append(toIndentedString(requestedPredicates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

