/*
 * Edison Credentials API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sicpa.edison.credentialsclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sicpa.edison.credentialsclient.model.RequestedAttribute;
import com.sicpa.edison.credentialsclient.model.RequestedPredicate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * The verification request
 */
@ApiModel(description = "The verification request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-23T15:13:07.571806+01:00[Europe/Zurich]")
public class VerificationRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_REQUESTED_ATTRIBUTES = "requestedAttributes";
  @SerializedName(SERIALIZED_NAME_REQUESTED_ATTRIBUTES)
  private List<RequestedAttribute> requestedAttributes = null;

  public static final String SERIALIZED_NAME_REQUESTED_PREDICATES = "requestedPredicates";
  @SerializedName(SERIALIZED_NAME_REQUESTED_PREDICATES)
  private List<RequestedPredicate> requestedPredicates = null;

  public static final String SERIALIZED_NAME_VALID_AT = "validAt";
  @SerializedName(SERIALIZED_NAME_VALID_AT)
  private OffsetDateTime validAt;


  public VerificationRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The verification request name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The verification request name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public VerificationRequest requestedAttributes(List<RequestedAttribute> requestedAttributes) {
    
    this.requestedAttributes = requestedAttributes;
    return this;
  }

  public VerificationRequest addRequestedAttributesItem(RequestedAttribute requestedAttributesItem) {
    if (this.requestedAttributes == null) {
      this.requestedAttributes = new ArrayList<>();
    }
    this.requestedAttributes.add(requestedAttributesItem);
    return this;
  }

   /**
   * The requested attributes
   * @return requestedAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The requested attributes")

  public List<RequestedAttribute> getRequestedAttributes() {
    return requestedAttributes;
  }


  public void setRequestedAttributes(List<RequestedAttribute> requestedAttributes) {
    this.requestedAttributes = requestedAttributes;
  }


  public VerificationRequest requestedPredicates(List<RequestedPredicate> requestedPredicates) {
    
    this.requestedPredicates = requestedPredicates;
    return this;
  }

  public VerificationRequest addRequestedPredicatesItem(RequestedPredicate requestedPredicatesItem) {
    if (this.requestedPredicates == null) {
      this.requestedPredicates = new ArrayList<>();
    }
    this.requestedPredicates.add(requestedPredicatesItem);
    return this;
  }

   /**
   * The requested predicates
   * @return requestedPredicates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The requested predicates")

  public List<RequestedPredicate> getRequestedPredicates() {
    return requestedPredicates;
  }


  public void setRequestedPredicates(List<RequestedPredicate> requestedPredicates) {
    this.requestedPredicates = requestedPredicates;
  }


  public VerificationRequest validAt(OffsetDateTime validAt) {
    
    this.validAt = validAt;
    return this;
  }

   /**
   * The date at which the credential should be valid
   * @return validAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date at which the credential should be valid")

  public OffsetDateTime getValidAt() {
    return validAt;
  }


  public void setValidAt(OffsetDateTime validAt) {
    this.validAt = validAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerificationRequest verificationRequest = (VerificationRequest) o;
    return Objects.equals(this.name, verificationRequest.name) &&
        Objects.equals(this.requestedAttributes, verificationRequest.requestedAttributes) &&
        Objects.equals(this.requestedPredicates, verificationRequest.requestedPredicates) &&
        Objects.equals(this.validAt, verificationRequest.validAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, requestedAttributes, requestedPredicates, validAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerificationRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    requestedAttributes: ").append(toIndentedString(requestedAttributes)).append("\n");
    sb.append("    requestedPredicates: ").append(toIndentedString(requestedPredicates)).append("\n");
    sb.append("    validAt: ").append(toIndentedString(validAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

