/*
 * Edison Credentials API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sicpa.edison.credentialsclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sicpa.edison.credentialsclient.model.WebhookWebhookTypeUpsert;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WebhookCreate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-08T17:35:55.199434+02:00[Europe/Zurich]")
public class WebhookCreate {
  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;

  public static final String SERIALIZED_NAME_WEBHOOK_TYPES = "webhookTypes";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_TYPES)
  private List<WebhookWebhookTypeUpsert> webhookTypes = new ArrayList<>();


  public WebhookCreate url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * The webhook&#39;s url
   * @return url
  **/
  @ApiModelProperty(required = true, value = "The webhook's url")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public WebhookCreate name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The webhook&#39;s name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "The webhook's name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public WebhookCreate active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Defines if the webhook is active or not
   * @return active
  **/
  @ApiModelProperty(required = true, value = "Defines if the webhook is active or not")

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  public WebhookCreate webhookTypes(List<WebhookWebhookTypeUpsert> webhookTypes) {
    
    this.webhookTypes = webhookTypes;
    return this;
  }

  public WebhookCreate addWebhookTypesItem(WebhookWebhookTypeUpsert webhookTypesItem) {
    this.webhookTypes.add(webhookTypesItem);
    return this;
  }

   /**
   * The webhook types associated with this webhook
   * @return webhookTypes
  **/
  @ApiModelProperty(required = true, value = "The webhook types associated with this webhook")

  public List<WebhookWebhookTypeUpsert> getWebhookTypes() {
    return webhookTypes;
  }


  public void setWebhookTypes(List<WebhookWebhookTypeUpsert> webhookTypes) {
    this.webhookTypes = webhookTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookCreate webhookCreate = (WebhookCreate) o;
    return Objects.equals(this.url, webhookCreate.url) &&
        Objects.equals(this.name, webhookCreate.name) &&
        Objects.equals(this.active, webhookCreate.active) &&
        Objects.equals(this.webhookTypes, webhookCreate.webhookTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, name, active, webhookTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookCreate {\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    webhookTypes: ").append(toIndentedString(webhookTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

