/*
 * Edison Credentials API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sicpa.edison.credentialsclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The webhook types associated with this webhook
 */
@ApiModel(description = "The webhook types associated with this webhook")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-23T15:13:07.571806+01:00[Europe/Zurich]")
public class WebhookWebhookTypeUpsert {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  private List<Integer> filters = null;


  public WebhookWebhookTypeUpsert id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * The webhook type id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The webhook type id")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public WebhookWebhookTypeUpsert filters(List<Integer> filters) {
    
    this.filters = filters;
    return this;
  }

  public WebhookWebhookTypeUpsert addFiltersItem(Integer filtersItem) {
    if (this.filters == null) {
      this.filters = new ArrayList<>();
    }
    this.filters.add(filtersItem);
    return this;
  }

   /**
   * List of webhook type filters id
   * @return filters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of webhook type filters id")

  public List<Integer> getFilters() {
    return filters;
  }


  public void setFilters(List<Integer> filters) {
    this.filters = filters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookWebhookTypeUpsert webhookWebhookTypeUpsert = (WebhookWebhookTypeUpsert) o;
    return Objects.equals(this.id, webhookWebhookTypeUpsert.id) &&
        Objects.equals(this.filters, webhookWebhookTypeUpsert.filters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, filters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookWebhookTypeUpsert {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

